### ISSUE TITLE
Remove serde and serde-cbor runtime dep

### ISSUE THREAD

**Issue by RCasatta** [bitcoindevkit/bitcoin-fee-model#1]
Read the `model.cbor` from the `build.rs` and generate a `model.rs` containing the model definition and instantiation in plain rust.

In alternative use proc macro.

The Model Data could potentially contain Arrays instead of Vec to work in no-std env. (using #[cfg(...)] if different sizes is needed)

**Comment by afilini** [comment]
Fixed #2
